baseURL: https://zwbetz.com
languageCode: en-us
defaultContentLanguage: en
title: zwbetz
theme: uswds-hugo-theme
enableRobotsTXT: true
timeout: 45000
enableGitInfo: true

build:
  writeStats: true

outputs:
  home:
    - HTML
    - RSS
    - JSON
  section:
    - HTML
    - RSS
    - JSON

disqusShortname:

disableKinds:
  - taxonomy
  - term

permalinks:
  blog: /:filename/

imaging:
  quality: 90

menu:
  nav:
    - name: Home
      pre: home
      url: /
      weight: 1
    - name: Blog
      pre: lightbulb
      url: /blog/
      weight: 2
    - name: Projects
      pre: build
      url: /projects/
      weight: 3

params:
  ga_measurement_id: G-8Y7T26BQ2T
  footer: >
    Made with [Hugo](https://gohugo.io/) &bull;
    Themed by [USWDS](https://github.com/zwbetz-gh/uswds-hugo-theme) &bull;
    Deployed by [Netlify](https://www.netlify.com/) &bull;
    Content in [GitHub](https://github.com/zwbetz-gh/zwbetz) &bull;
    See an issue? [Let me know 🙂](https://github.com/zwbetz-gh/zwbetz/issues/new/choose)
  show_footer_site_last_updated: false
  show_footer_debug: false
  search: true
  search_minify: true
  show_prev_next_links: false
  show_tags: false
  use_purged_css: false
  use_nav_icon: true

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: false
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: true
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: pygments
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2
