baseURL: https://zwbetz.com/
languageCode: en-us
defaultContentLanguage: en
title: zwbetz
theme: uswds-hugo-theme
enableRobotsTXT: true
timeout: 45000
googleAnalytics: UA-115738775-1
enableGitInfo: true

outputs:
  home: [HTML, RSS, JSON]

pygmentsCodefences: true
pygmentsStyle: pygments

disqusShortname:

taxonomies:
  tag: tags

permalinks:
  blog: /:filename/

imaging:
  quality: 90

menu:
  nav:
    - name: Home
      url: /
      weight: 1
    - name: Blog
      url: /blog/
      weight: 2
    - name: Tags
      url: /tags/
      weight: 3
    - name: RSS
      url: /index.xml
      weight: 4

params:
  footer: >
    Made with [Hugo](https://gohugo.io/) &bull;
    Themed by [USWDS](https://designsystem.digital.gov/) &bull;
    Deployed to [Netlify](https://www.netlify.com/) &bull;
    Content in [Git](https://github.com/zwbetz-gh/zwbetz)
