baseURL: https://zwbetz.com
languageCode: en-us
defaultContentLanguage: en
title: zwbetz
theme: uswds-hugo-theme
enableRobotsTXT: true
timeout: 45000
googleAnalytics: UA-115738775-1
enableGitInfo: true

outputs:
  home:
    - HTML
    - RSS
    - JSON

disqusShortname:

disableKinds:
  - taxonomy
  - term

permalinks:
  blog: /:filename/

imaging:
  quality: 90

menu:
  nav:
    - name: Home
      url: /
      weight: 1
    - name: Blog
      url: /blog/
      weight: 2
    - name: Projects
      url: /projects/
      weight: 3
    - name: JSON
      url: /index.json
      weight: 4
    - name: RSS
      url: /index.xml
      weight: 5

params:
  footer: >
    Made with [Hugo](https://gohugo.io/) &bull;
    Themed by [USWDS](https://designsystem.digital.gov/) &bull;
    Deployed by [Netlify](https://www.netlify.com/) &bull;
    Content in [GitHub](https://github.com/zwbetz-gh/zwbetz)
  show_footer_site_last_updated: false
  show_footer_debug: true
  search: true
  show_prev_next_links: false
  show_tags: false

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: false
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: true
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: pygments
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2
