[build]
  publish = "public"
  command = "chmod 755 task_resume_get.sh task_site_build.sh && ./task_site_build.sh"

[build.environment]
  HUGO_VERSION = "0.103.1"
  NODE_VERSION = "16"

[build.processing.images]
  compress = true
